import type { Database } from '@/lib/supabase/types';
import { DEMO_CASE_IDS, DEMO_OFFICER_ID } from './cases';

type AuditLogInsert = Database['public']['Tables']['audit_logs']['Insert'];

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000).toISOString();
const minsAfter = (base: number, m: number) =>
  new Date(now.getTime() - base * 3600000 + m * 60000).toISOString();

export const demoAuditLogs: AuditLogInsert[] = [
  // ========================================
  // Case 1: Sarah Chen - Full lifecycle
  // ========================================
  {
    id: '40000000-0000-0000-0000-000000000001',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'case.created',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Case created for applicant Sarah Chen',
      metadata: { applicant_email: 'sarah.chen@example.com' },
    },
    created_at: hoursAgo(48),
  },
  {
    id: '40000000-0000-0000-0000-000000000002',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'case.documents_uploaded',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Documents uploaded: sarah_chen_passport.pdf, sarah_chen_hydro_bill.pdf',
      metadata: { document_count: 2 },
    },
    created_at: hoursAgo(48),
  },
  {
    id: '40000000-0000-0000-0000-000000000003',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'pipeline.started',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'system_event',
      description: 'KYC processing pipeline initiated',
    },
    created_at: hoursAgo(48),
  },
  {
    id: '40000000-0000-0000-0000-000000000004',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'document_processor',
    details: {
      event_type: 'agent_action',
      agent_type: 'document_processor',
      input_summary: '2 documents submitted for OCR processing',
      output_summary: 'Extracted 6 fields from passport, 4 fields from utility bill',
      confidence: 0.95,
      duration_ms: 6050,
      success: true,
      model_used: 'mistral-ocr + gemini-2.5-flash',
    },
    created_at: minsAfter(48, 0.4),
  },
  {
    id: '40000000-0000-0000-0000-000000000005',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'identity_verifier',
    details: {
      event_type: 'agent_action',
      agent_type: 'identity_verifier',
      input_summary: 'Verifying identity for Sarah Chen against 3 extracted fields',
      output_summary: 'All identity fields verified. No discrepancies.',
      confidence: 0.94,
      duration_ms: 48000,
      success: true,
      model_used: 'gemini-2.5-pro',
    },
    created_at: minsAfter(48, 1.2),
  },
  {
    id: '40000000-0000-0000-0000-000000000006',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'sanctions_screener',
    details: {
      event_type: 'agent_action',
      agent_type: 'sanctions_screener',
      input_summary: 'Screening Sarah Chen against OFAC, UN, PEP databases',
      output_summary: 'No matches found across all databases',
      confidence: 0.99,
      duration_ms: 42000,
      success: true,
      model_used: 'gemini-2.5-flash',
    },
    created_at: minsAfter(48, 1.1),
  },
  {
    id: '40000000-0000-0000-0000-000000000007',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'risk_scorer',
    details: {
      event_type: 'agent_action',
      agent_type: 'risk_scorer',
      input_summary: 'Calculating composite risk score',
      output_summary: 'Risk score: 12/100 (Low). No manual review required.',
      confidence: 0.96,
      duration_ms: 36000,
      success: true,
      model_used: 'deterministic',
    },
    created_at: minsAfter(48, 1.8),
  },
  {
    id: '40000000-0000-0000-0000-000000000008',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'case_narrator',
    details: {
      event_type: 'agent_action',
      agent_type: 'case_narrator',
      input_summary: 'Generating compliance narrative for low-risk case',
      output_summary: 'Narrative generated with 3 key findings. Recommended action: approve.',
      confidence: 0.95,
      duration_ms: 42000,
      success: true,
      model_used: 'gemini-2.5-pro',
    },
    created_at: minsAfter(48, 2.5),
  },
  {
    id: '40000000-0000-0000-0000-000000000009',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'pipeline.completed',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'system_event',
      description: 'KYC processing pipeline completed successfully',
      metadata: { total_duration_ms: 148200, agents_completed: 5 },
    },
    created_at: minsAfter(48, 2.5),
  },
  {
    id: '40000000-0000-0000-0000-000000000010',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'case.status_changed',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Case status changed from processing to review',
      metadata: { previous_status: 'processing', new_status: 'review' },
    },
    created_at: minsAfter(48, 2.5),
  },
  {
    id: '40000000-0000-0000-0000-000000000011',
    case_id: DEMO_CASE_IDS.SARAH_CHEN,
    action: 'decision.approved',
    actor_type: 'officer',
    actor_id: DEMO_OFFICER_ID,
    details: {
      event_type: 'human_decision',
      decision: 'approved',
      justification: 'All identity documents verified with high confidence. No sanctions matches. Low risk score of 12. Standard onboarding approved.',
      officer_id: DEMO_OFFICER_ID,
      officer_name: 'Demo Compliance Officer',
      case_risk_score: 12,
      case_risk_level: 'low',
      previous_status: 'review',
      new_status: 'approved',
    },
    created_at: hoursAgo(47),
  },

  // ========================================
  // Case 2: Viktor Petrov - Full lifecycle + escalation + STR
  // ========================================
  {
    id: '40000000-0000-0000-0000-000000000012',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'case.created',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Case created for applicant Viktor Petrov',
      metadata: { applicant_email: 'v.petrov@mail.ru' },
    },
    created_at: hoursAgo(36),
  },
  {
    id: '40000000-0000-0000-0000-000000000013',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'case.documents_uploaded',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Documents uploaded: viktor_petrov_passport.pdf',
      metadata: { document_count: 1 },
    },
    created_at: hoursAgo(36),
  },
  {
    id: '40000000-0000-0000-0000-000000000014',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'pipeline.started',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'system_event',
      description: 'KYC processing pipeline initiated',
    },
    created_at: hoursAgo(36),
  },
  {
    id: '40000000-0000-0000-0000-000000000015',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'document_processor',
    details: {
      event_type: 'agent_action',
      agent_type: 'document_processor',
      input_summary: '1 document submitted for OCR processing',
      output_summary: 'Extracted 6 fields from Russian passport. Document shows physical wear.',
      confidence: 0.88,
      duration_ms: 4120,
      success: true,
      model_used: 'mistral-ocr + gemini-2.5-flash',
    },
    created_at: minsAfter(36, 0.5),
  },
  {
    id: '40000000-0000-0000-0000-000000000016',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'identity_verifier',
    details: {
      event_type: 'agent_action',
      agent_type: 'identity_verifier',
      input_summary: 'Verifying identity for Viktor Petrov against 2 extracted fields',
      output_summary: 'Identity confirmed. Single document verification.',
      confidence: 0.87,
      duration_ms: 54000,
      success: true,
      model_used: 'gemini-2.5-pro',
    },
    created_at: minsAfter(36, 1.4),
  },
  {
    id: '40000000-0000-0000-0000-000000000017',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'sanctions_screener',
    details: {
      event_type: 'agent_action',
      agent_type: 'sanctions_screener',
      input_summary: 'Screening Viktor Petrov against OFAC, UN, PEP databases',
      output_summary: 'ALERT: OFAC SDN match at 94% (Viktor A. Petrov, OFAC-29847). UN potential match at 67%.',
      confidence: 0.94,
      duration_ms: 66000,
      success: true,
      model_used: 'gemini-2.5-flash',
    },
    created_at: minsAfter(36, 1.6),
  },
  {
    id: '40000000-0000-0000-0000-000000000018',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'risk_scorer',
    details: {
      event_type: 'agent_action',
      agent_type: 'risk_scorer',
      input_summary: 'Calculating composite risk score with sanctions match',
      output_summary: 'Risk score: 87/100 (Critical). Immediate escalation required.',
      confidence: 0.91,
      duration_ms: 42000,
      success: true,
      model_used: 'deterministic',
    },
    created_at: minsAfter(36, 2.3),
  },
  {
    id: '40000000-0000-0000-0000-000000000019',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'case_narrator',
    details: {
      event_type: 'agent_action',
      agent_type: 'case_narrator',
      input_summary: 'Generating compliance narrative for critical-risk case',
      output_summary: 'Narrative generated with 4 key findings. Recommended action: escalate. STR recommended.',
      confidence: 0.92,
      duration_ms: 48000,
      success: true,
      model_used: 'gemini-2.5-pro',
    },
    created_at: minsAfter(36, 3.1),
  },
  {
    id: '40000000-0000-0000-0000-000000000020',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'pipeline.completed',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'system_event',
      description: 'KYC processing pipeline completed. ALERT: Sanctions match detected.',
      metadata: { total_duration_ms: 186000, agents_completed: 5, sanctions_alert: true },
    },
    created_at: minsAfter(36, 3.1),
  },
  {
    id: '40000000-0000-0000-0000-000000000021',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'case.status_changed',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Case status changed from processing to review',
      metadata: { previous_status: 'processing', new_status: 'review' },
    },
    created_at: minsAfter(36, 3.1),
  },
  {
    id: '40000000-0000-0000-0000-000000000022',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'decision.escalated',
    actor_type: 'officer',
    actor_id: DEMO_OFFICER_ID,
    details: {
      event_type: 'human_decision',
      decision: 'escalated',
      justification: 'OFAC SDN match at 94% confidence requires immediate escalation. Applicant name matches sanctioned individual Viktor A. Petrov (OFAC ID: 29847). Potential STR filing required under FINTRAC guidelines.',
      officer_id: DEMO_OFFICER_ID,
      officer_name: 'Demo Compliance Officer',
      case_risk_score: 87,
      case_risk_level: 'critical',
      previous_status: 'review',
      new_status: 'escalated',
    },
    created_at: hoursAgo(35),
  },
  {
    id: '40000000-0000-0000-0000-000000000023',
    case_id: DEMO_CASE_IDS.VIKTOR_PETROV,
    action: 'decision.str_referred',
    actor_type: 'officer',
    actor_id: DEMO_OFFICER_ID,
    details: {
      event_type: 'human_decision',
      decision: 'str_referral',
      justification: 'Suspicious Transaction Report filed with FINTRAC. OFAC SDN match confirmed. Case referred to senior compliance and legal review.',
      officer_id: DEMO_OFFICER_ID,
      officer_name: 'Demo Compliance Officer',
      case_risk_score: 87,
      case_risk_level: 'critical',
      previous_status: 'escalated',
      new_status: 'escalated',
    },
    created_at: hoursAgo(34),
  },

  // ========================================
  // Case 3: Amara Okafor - Up to processing_completed
  // ========================================
  {
    id: '40000000-0000-0000-0000-000000000024',
    case_id: DEMO_CASE_IDS.AMARA_OKAFOR,
    action: 'case.created',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Case created for applicant Amara Okafor',
      metadata: { applicant_email: 'amara.okafor@gmail.com' },
    },
    created_at: hoursAgo(12),
  },
  {
    id: '40000000-0000-0000-0000-000000000025',
    case_id: DEMO_CASE_IDS.AMARA_OKAFOR,
    action: 'case.documents_uploaded',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Documents uploaded: amara_okafor_license.jpg',
      metadata: { document_count: 1 },
    },
    created_at: hoursAgo(12),
  },
  {
    id: '40000000-0000-0000-0000-000000000026',
    case_id: DEMO_CASE_IDS.AMARA_OKAFOR,
    action: 'pipeline.started',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'system_event',
      description: 'KYC processing pipeline initiated',
    },
    created_at: hoursAgo(12),
  },
  {
    id: '40000000-0000-0000-0000-000000000027',
    case_id: DEMO_CASE_IDS.AMARA_OKAFOR,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'document_processor',
    details: {
      event_type: 'agent_action',
      agent_type: 'document_processor',
      input_summary: '1 document submitted for OCR processing',
      output_summary: 'Extracted 5 fields. Low quality (0.62) — image at angle with glare.',
      confidence: 0.62,
      duration_ms: 5870,
      success: true,
      model_used: 'mistral-ocr + gemini-2.5-flash',
    },
    created_at: minsAfter(12, 0.7),
  },
  {
    id: '40000000-0000-0000-0000-000000000028',
    case_id: DEMO_CASE_IDS.AMARA_OKAFOR,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'sanctions_screener',
    details: {
      event_type: 'agent_action',
      agent_type: 'sanctions_screener',
      input_summary: 'Screening Amara Okafor against OFAC, UN, PEP databases',
      output_summary: 'No matches found across all databases',
      confidence: 0.98,
      duration_ms: 42000,
      success: true,
      model_used: 'gemini-2.5-flash',
    },
    created_at: minsAfter(12, 1.4),
  },
  {
    id: '40000000-0000-0000-0000-000000000029',
    case_id: DEMO_CASE_IDS.AMARA_OKAFOR,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'identity_verifier',
    details: {
      event_type: 'agent_action',
      agent_type: 'identity_verifier',
      input_summary: 'Verifying identity for Amara Okafor against 2 extracted fields',
      output_summary: 'Partial verification. Name discrepancy: middle initial on document.',
      confidence: 0.71,
      duration_ms: 48000,
      success: true,
      model_used: 'gemini-2.5-pro',
    },
    created_at: minsAfter(12, 1.5),
  },
  {
    id: '40000000-0000-0000-0000-000000000030',
    case_id: DEMO_CASE_IDS.AMARA_OKAFOR,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'risk_scorer',
    details: {
      event_type: 'agent_action',
      agent_type: 'risk_scorer',
      input_summary: 'Calculating composite risk score with document quality concerns',
      output_summary: 'Risk score: 45/100 (Medium). Manual review recommended.',
      confidence: 0.78,
      duration_ms: 42000,
      success: true,
      model_used: 'deterministic',
    },
    created_at: minsAfter(12, 2.2),
  },
  {
    id: '40000000-0000-0000-0000-000000000031',
    case_id: DEMO_CASE_IDS.AMARA_OKAFOR,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'case_narrator',
    details: {
      event_type: 'agent_action',
      agent_type: 'case_narrator',
      input_summary: 'Generating compliance narrative for medium-risk case',
      output_summary: 'Narrative generated with 4 key findings. Recommended action: manual review.',
      confidence: 0.76,
      duration_ms: 72000,
      success: true,
      model_used: 'gemini-2.5-pro',
    },
    created_at: minsAfter(12, 3.4),
  },
  {
    id: '40000000-0000-0000-0000-000000000032',
    case_id: DEMO_CASE_IDS.AMARA_OKAFOR,
    action: 'pipeline.completed',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'system_event',
      description: 'KYC processing pipeline completed. Manual review required.',
      metadata: { total_duration_ms: 204000, agents_completed: 5 },
    },
    created_at: minsAfter(12, 3.4),
  },
  {
    id: '40000000-0000-0000-0000-000000000033',
    case_id: DEMO_CASE_IDS.AMARA_OKAFOR,
    action: 'case.status_changed',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Case status changed from processing to review',
      metadata: { previous_status: 'processing', new_status: 'review' },
    },
    created_at: minsAfter(12, 3.4),
  },

  // ========================================
  // Case 4: Maria Gonzalez-Rivera - Up to processing_completed
  // ========================================
  {
    id: '40000000-0000-0000-0000-000000000034',
    case_id: DEMO_CASE_IDS.MARIA_GONZALEZ,
    action: 'case.created',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Case created for applicant Maria Gonzalez-Rivera',
      metadata: { applicant_email: 'mgonzalez@diplomatico.mx' },
    },
    created_at: hoursAgo(8),
  },
  {
    id: '40000000-0000-0000-0000-000000000035',
    case_id: DEMO_CASE_IDS.MARIA_GONZALEZ,
    action: 'case.documents_uploaded',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Documents uploaded: maria_gonzalez_passport.pdf, maria_gonzalez_enbridge_bill.pdf',
      metadata: { document_count: 2 },
    },
    created_at: hoursAgo(8),
  },
  {
    id: '40000000-0000-0000-0000-000000000036',
    case_id: DEMO_CASE_IDS.MARIA_GONZALEZ,
    action: 'pipeline.started',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'system_event',
      description: 'KYC processing pipeline initiated',
    },
    created_at: hoursAgo(8),
  },
  {
    id: '40000000-0000-0000-0000-000000000037',
    case_id: DEMO_CASE_IDS.MARIA_GONZALEZ,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'document_processor',
    details: {
      event_type: 'agent_action',
      agent_type: 'document_processor',
      input_summary: '2 documents submitted for OCR processing',
      output_summary: 'Extracted 6 fields from passport, 4 from utility bill. Good quality.',
      confidence: 0.92,
      duration_ms: 6230,
      success: true,
      model_used: 'mistral-ocr + gemini-2.5-flash',
    },
    created_at: minsAfter(8, 0.5),
  },
  {
    id: '40000000-0000-0000-0000-000000000038',
    case_id: DEMO_CASE_IDS.MARIA_GONZALEZ,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'identity_verifier',
    details: {
      event_type: 'agent_action',
      agent_type: 'identity_verifier',
      input_summary: 'Verifying identity for Maria Gonzalez-Rivera against 3 extracted fields',
      output_summary: 'Identity verified. Middle name "Elena" on passport is acceptable variation.',
      confidence: 0.91,
      duration_ms: 48000,
      success: true,
      model_used: 'gemini-2.5-pro',
    },
    created_at: minsAfter(8, 1.3),
  },
  {
    id: '40000000-0000-0000-0000-000000000039',
    case_id: DEMO_CASE_IDS.MARIA_GONZALEZ,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'sanctions_screener',
    details: {
      event_type: 'agent_action',
      agent_type: 'sanctions_screener',
      input_summary: 'Screening Maria Gonzalez-Rivera against OFAC, UN, PEP databases',
      output_summary: 'PEP match: Maria Elena Gonzalez-Rivera, Mexican Deputy Ambassador (89%). No OFAC/UN matches.',
      confidence: 0.89,
      duration_ms: 60000,
      success: true,
      model_used: 'gemini-2.5-flash',
    },
    created_at: minsAfter(8, 1.5),
  },
  {
    id: '40000000-0000-0000-0000-000000000040',
    case_id: DEMO_CASE_IDS.MARIA_GONZALEZ,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'risk_scorer',
    details: {
      event_type: 'agent_action',
      agent_type: 'risk_scorer',
      input_summary: 'Calculating composite risk score with PEP match',
      output_summary: 'Risk score: 68/100 (High). Enhanced due diligence required.',
      confidence: 0.86,
      duration_ms: 42000,
      success: true,
      model_used: 'deterministic',
    },
    created_at: minsAfter(8, 2.2),
  },
  {
    id: '40000000-0000-0000-0000-000000000041',
    case_id: DEMO_CASE_IDS.MARIA_GONZALEZ,
    action: 'agent.completed',
    actor_type: 'agent',
    actor_id: 'case_narrator',
    details: {
      event_type: 'agent_action',
      agent_type: 'case_narrator',
      input_summary: 'Generating compliance narrative for high-risk PEP case',
      output_summary: 'Narrative generated with 4 key findings. Recommended action: enhanced due diligence.',
      confidence: 0.85,
      duration_ms: 48000,
      success: true,
      model_used: 'gemini-2.5-pro',
    },
    created_at: minsAfter(8, 3.0),
  },
  {
    id: '40000000-0000-0000-0000-000000000042',
    case_id: DEMO_CASE_IDS.MARIA_GONZALEZ,
    action: 'pipeline.completed',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'system_event',
      description: 'KYC processing pipeline completed. PEP match requires enhanced due diligence.',
      metadata: { total_duration_ms: 180000, agents_completed: 5, pep_alert: true },
    },
    created_at: minsAfter(8, 3.0),
  },
  {
    id: '40000000-0000-0000-0000-000000000043',
    case_id: DEMO_CASE_IDS.MARIA_GONZALEZ,
    action: 'case.status_changed',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Case status changed from processing to review',
      metadata: { previous_status: 'processing', new_status: 'review' },
    },
    created_at: minsAfter(8, 3.0),
  },

  // ========================================
  // Case 5: James Oduya - Only created + processing_started
  // ========================================
  {
    id: '40000000-0000-0000-0000-000000000044',
    case_id: DEMO_CASE_IDS.JAMES_ODUYA,
    action: 'case.created',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Case created for applicant James Oduya',
      metadata: { applicant_email: 'james.oduya@outlook.com' },
    },
    created_at: hoursAgo(1),
  },
  {
    id: '40000000-0000-0000-0000-000000000045',
    case_id: DEMO_CASE_IDS.JAMES_ODUYA,
    action: 'case.documents_uploaded',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'case_lifecycle',
      description: 'Documents uploaded: james_oduya_passport.pdf, james_oduya_epcor_bill.pdf, james_oduya_td_statement.pdf',
      metadata: { document_count: 3 },
    },
    created_at: hoursAgo(1),
  },
  {
    id: '40000000-0000-0000-0000-000000000046',
    case_id: DEMO_CASE_IDS.JAMES_ODUYA,
    action: 'pipeline.started',
    actor_type: 'system',
    actor_id: 'system',
    details: {
      event_type: 'system_event',
      description: 'KYC processing pipeline initiated. 3 documents queued for processing.',
    },
    created_at: hoursAgo(1),
  },
];
